package com.dfans.model;

public class Activity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.id
     *
     * @mbggenerated Sat Jun 29 20:52:18 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.acti_name
     *
     * @mbggenerated Sat Jun 29 20:52:18 CST 2019
     */
    private String actiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.acti_time
     *
     * @mbggenerated Sat Jun 29 20:52:18 CST 2019
     */
    private String actiTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.acti_addr
     *
     * @mbggenerated Sat Jun 29 20:52:18 CST 2019
     */
    private String actiAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.acti_disc
     *
     * @mbggenerated Sat Jun 29 20:52:18 CST 2019
     */
    private String actiDisc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.id
     *
     * @return the value of activity.id
     *
     * @mbggenerated Sat Jun 29 20:52:18 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.id
     *
     * @param id the value for activity.id
     *
     * @mbggenerated Sat Jun 29 20:52:18 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.acti_name
     *
     * @return the value of activity.acti_name
     *
     * @mbggenerated Sat Jun 29 20:52:18 CST 2019
     */
    public String getActiName() {
        return actiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.acti_name
     *
     * @param actiName the value for activity.acti_name
     *
     * @mbggenerated Sat Jun 29 20:52:18 CST 2019
     */
    public void setActiName(String actiName) {
        this.actiName = actiName == null ? null : actiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.acti_time
     *
     * @return the value of activity.acti_time
     *
     * @mbggenerated Sat Jun 29 20:52:18 CST 2019
     */
    public String getActiTime() {
        return actiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.acti_time
     *
     * @param actiTime the value for activity.acti_time
     *
     * @mbggenerated Sat Jun 29 20:52:18 CST 2019
     */
    public void setActiTime(String actiTime) {
        this.actiTime = actiTime == null ? null : actiTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.acti_addr
     *
     * @return the value of activity.acti_addr
     *
     * @mbggenerated Sat Jun 29 20:52:18 CST 2019
     */
    public String getActiAddr() {
        return actiAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.acti_addr
     *
     * @param actiAddr the value for activity.acti_addr
     *
     * @mbggenerated Sat Jun 29 20:52:18 CST 2019
     */
    public void setActiAddr(String actiAddr) {
        this.actiAddr = actiAddr == null ? null : actiAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.acti_disc
     *
     * @return the value of activity.acti_disc
     *
     * @mbggenerated Sat Jun 29 20:52:18 CST 2019
     */
    public String getActiDisc() {
        return actiDisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.acti_disc
     *
     * @param actiDisc the value for activity.acti_disc
     *
     * @mbggenerated Sat Jun 29 20:52:18 CST 2019
     */
    public void setActiDisc(String actiDisc) {
        this.actiDisc = actiDisc == null ? null : actiDisc.trim();
    }
	@Override
	public String toString() {
		return "Activity [id=" + id + ", actiName=" + actiName + ", actiTime=" + actiTime + ", actiAddr=" + actiAddr
				+ ", actiDisc=" + actiDisc + "]";
	}
    
    
}